FROM jrottenberg/ffmpeg:7.1.1-alpine320

WORKDIR /app

COPY requirements.txt requirements.txt
COPY vtask vtask

RUN apk add --no-cache python3 py3-pip git

RUN python3 -m venv .venv
RUN .venv/bin/pip3 install -r requirements.txt
