FROM jrottenberg/ffmpeg:7.1.1-nvidia2404

WORKDIR /app

COPY requirements.txt requirements.txt
COPY vidt vidt

RUN apt-get update
RUN apt-get install -y python3 python3-pip python3-venv git

RUN python3 -m venv .venv
RUN .venv/bin/pip3 install -r requirements.txt
