FROM python:3.13.2-alpine

WORKDIR /app

COPY requirements.txt requirements.txt
COPY assets/ffmpeg-release-amd64-static.tar.xz ffmpeg-release-amd64-static.tar.xz

RUN apk add git

RUN tar -xvf ffmpeg-release-amd64-static.tar.xz && \
    chmod +x ffmpeg-7.0.2-amd64-static/ffmpeg && \
    mv ffmpeg-7.0.2-amd64-static/ffmpeg /usr/local/bin/ffmpeg && \
    rm -rf ffmpeg-release-amd64-static.tar.xz ffmpeg-7.0.2-amd64-static

RUN pip install -r requirements.txt
