FROM nvidia/cuda:12.6.1-runtime-ubuntu22.04

WORKDIR /app

COPY requirements.txt requirements.txt
COPY vtask vtask

RUN apt-get update
RUN apt-get install -y python3 python3-pip git ffmpeg

RUN pip install -r requirements.txt
