DEFAULT_WORKER_NAME = "default"
IO_LFS_WORKER_NAME = "io.lfs"
IO_NET_WORKER_NAME = "io.net"
CPU_SINGLE_WORKER_NAME = "cpu.single"
CPU_MULTIPLE_WORKER_NAME = "cpu.multiple"

DEFAULT_QUEUE_NAME = "celery:vtask:default"
IO_LFS_QUEUE_NAME = "celery:vtask:io:lfs"
IO_NET_QUEUE_NAME = "celery:vtask:io:net"
CPU_SINGLE_QUEUE_NAME = "celery:vtask:cpu:single"
CPU_MULTIPLE_QUEUE_NAME = "celery:vtask:cpu:multiple"
