apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}-server
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.global.name }}-server
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      {{ if .Values.server.service.nodePort }}
      nodePort: {{ .Values.server.service.nodePort }}
      {{ end }}
